Repository AdobeDocs/commerce-services, pull requests merged in 2023-11, with the labels that each got.

#72 Update workflows with deployments
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#71 COMDOX-804 Migrate Services GraphQL topics
  src/_includes/graphql/catalog-service/categories.md
  src/_includes/graphql/catalog-service/headers.md
  src/_includes/graphql/catalog-service/product-view.md
  src/_includes/graphql/live-search-headers.md
  src/data/navigation/header.js
  src/data/navigation/sections/graphql.js
  src/data/navigation/sections/index.js
  src/pages/graphql/catalog-service/categories.md
  src/pages/graphql/catalog-service/index.md
  src/pages/graphql/catalog-service/product-search.md
  src/pages/graphql/catalog-service/products.md
  src/pages/graphql/catalog-service/refine-product.md
  src/pages/graphql/index.md
  src/pages/graphql/live-search/attribute-metadata.md
  src/pages/graphql/live-search/index.md
  src/pages/graphql/live-search/product-search.md
  src/pages/graphql/recommendations/index.md
  src/pages/graphql/recommendations/recommendations.md
Labels: migration, maintenance, internal

#74 Sync deployment workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
Labels: maintenance

#76 Update theme and caniuse-lite
  package.json
  yarn.lock
Labels: dependencies

#75 Add a linter to validate external links
  .remarkrc.mjs
  package.json
  src/pages/live-search/index.md
  src/pages/product-recommendations/index.md
  src/pages/reporting/import-api.md
  src/pages/reporting/libraries.md
  src/pages/shared-services/storefront-events/collector/index.md
  src/pages/shared-services/storefront-events/sdk/index.md
  yarn.lock
Labels: enhancement

#78 Add validation for custom headers
  .remarkrc.mjs
  package.json
  yarn.lock
Labels: enhancement
