Repository AdobeDocs/commerce-services, pull requests merged in 2024-08, with the labels that each got.

#129 Updates for Customer Group required header description
  src/_includes/graphql/catalog-service/headers.md
  src/_includes/graphql/customer-group-code.md
  src/pages/graphql/catalog-service/categories.md
  src/pages/graphql/catalog-service/products.md
  src/pages/graphql/catalog-service/refine-product.md
  src/pages/graphql/live-search/product-search.md
  src/pages/graphql/recommendations/recommendations.md
Labels: internal, technical

#132 Refactor GitHub Actions workflows
  .github/super-linter.env
  .github/workflows/github-pages.yml
  .github/workflows/index.yml
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
Labels: maintenance, internal

#135 Adding link to live search guide
  src/pages/graphql/live-search/product-search.md
Labels: editorial

#136 DATA-6039: Add Catalog service variants query
  src/data/navigation/sections/graphql.js
  src/pages/graphql/catalog-service/index.md
  src/pages/graphql/catalog-service/product-variants.md
Labels: new-topic
