Repository AdobeDocs/commerce-services, pull requests merged in 2024-12, with the labels that each got.

#170 Fix github-pages workflow in private repos
  .github/workflows/github-pages.yml
  .gitignore
Labels: enhancement

#172 Update policy header description in composable-catalog docs
  src/pages/composable-catalog/storefront-services/using-the-api.md
  static/graphql-api/admin-api/index.html
  static/graphql-api/storefront-api/index.html
Labels: major-update, internal

#173 [CCDM] DCAT-2098: configurable products
  src/openapi/data-ingestion-schema-v1.yaml
Labels: internal, technical

#174 [CCDM] DCAT-2110: update "roles"
  src/openapi/data-ingestion-schema-v1.yaml
Labels: internal, technical

#176 [CCDM] DCAT-2079 response object
  src/openapi/data-ingestion-schema-v1.yaml
Labels: internal, technical

#177 Trigger staging workflow on each push to ccdm-early-access
  .github/workflows/stage.yml
Labels: maintenance

#179 Update GitHub workflows
  .github/workflows/publish.yml
  .github/workflows/stage.yml
  .github/workflows/test-pull-request.yml
  package.json
Labels: maintenance

#178 COMDOX-1116: Enable OpenAPI linting
  .github/super-linter.env
  src/openapi/data-ingestion-schema-v1.yaml
Labels: maintenance
