Repository AdobeDocs/commerce-services, pull requests merged in 2024-11, with the labels that each got.

#148 Update ProductView object to add new schema fields - merge when CS v1.26 is released
  src/_includes/graphql/catalog-service/product-view.md
Labels: technical

#141 Apply code block formatting
  src/pages/graphql/catalog-service/categories.md
  src/pages/graphql/catalog-service/product-variants.md
  src/pages/graphql/catalog-service/products.md
  src/pages/graphql/catalog-service/refine-product.md
Labels: editorial, internal

#162 Run staging workflow only for the ccdm-publish-to-staging branch
  .github/workflows/stage.yml
Labels: maintenance

#164 Update the branch name set for staging
  .github/workflows/stage.yml
Labels: maintenance

#149 CCDM developer documentation architecture
  package.json
  spectaql/config-admin.yml
  spectaql/config-storefront.yml
  spectaql/storefront-api-schema.json
  src/data/navigation/header.js
  src/data/navigation/sections/composable-catalog.js
  src/openapi/.redocly.yaml
  src/openapi/data-ingestion-schema-v1.yaml
  src/pages/composable-catalog/admin/api-reference.md
  src/pages/composable-catalog/admin/index.md
  src/pages/composable-catalog/admin/limits.md
  src/pages/composable-catalog/admin/using-the-api.md
  src/pages/composable-catalog/data-ingestion/api-reference.md
  src/pages/composable-catalog/data-ingestion/limits.md
  src/pages/composable-catalog/data-ingestion/using-the-api.md
  src/pages/composable-catalog/index.md
  src/pages/composable-catalog/manage-catalog-data.md
  src/pages/composable-catalog/manage-catalogs.md
  src/pages/composable-catalog/merchandising/api-reference.md
  src/pages/composable-catalog/merchandising/limits.md
  src/pages/composable-catalog/merchandising/using-the-api.md
  src/pages/composable-catalog/storefront-services/api-reference.md
  src/pages/composable-catalog/storefront-services/index.md
  src/pages/composable-catalog/storefront-services/using-the-api.md
  src/pages/index.md
  static/graphql-api/admin-api/index.html
  static/graphql-api/admin-api/javascripts/spectaql.min.js
  static/graphql-api/admin-api/stylesheets/spectaql.min.css
  static/graphql-api/storefront-api/index.html
  static/graphql-api/storefront-api/javascripts/spectaql.min.js
  static/graphql-api/storefront-api/stylesheets/spectaql.min.css
  yarn.lock
Labels: major-update

#166 Use URL instead of a schema file for Storefront API Reference
  spectaql/config-storefront.yml
  spectaql/storefront-api-schema.json
  static/graphql-api/storefront-api/index.html
Labels: technical

#168 Update api-reference.md
  src/pages/composable-catalog/data-ingestion/api-reference.md
Labels: technical

#167 DCAT-2088: Add instructions for generating API references
  .gitignore
  README.md
  src/openapi/.redocly.yaml
  src/openapi/README.md
  src/pages/composable-catalog/data-ingestion/api-reference.md
Labels: maintenance
