Repository AdobeDocs/commerce-services, pull requests merged in 2024-06, with the labels that each got.

#108 Add links to API playground
  src/pages/graphql/catalog-service/products.md
  src/pages/graphql/index.md
  src/pages/graphql/recommendations/recommendations.md
Labels: editorial, internal

#107 Upgrade theme to v4.11.14
  package.json
  yarn.lock
Labels: dependencies, internal

#111 Combining productSearch query
  src/data/navigation/sections/graphql.js
  src/pages/graphql/catalog-service/index.md
  src/pages/graphql/catalog-service/product-search.md
  src/pages/graphql/index.md
  src/pages/graphql/live-search/product-search.md
Labels: enhancement
