Repository AdobeDocs/commerce-services, pull requests merged in 2025-05, with the labels that each got.

#236 docs: add info about edition component
  README.md
  src/pages/graphql/index.md
Labels: maintenance

#237 COMOPT-383: Use ComOpt UI for channels and policies
  src/pages/composable-catalog/ccdm-use-case.md
  src/pages/graphql/index.md
Labels: technical

#239 Disable external link checking
  .remarkrc.mjs
  .remarkrc.yml
  package.json
  yarn.lock
Labels: maintenance

#241 Fix: analytics tracking
  gatsby-browser.js
Labels: maintenance, internal
