Repository AdobeDocs/commerce-services, pull requests merged in 2025-08, with the labels that each got.

#280 Update Data Ingestion API
  src/pages/optimizer/data-ingestion/api-reference.md
  src/pages/optimizer/data-ingestion/using-the-api.md
  src/pages/reference/rest/index.md
Labels: internal, technical

#283 feat: change trigger to workflow dispatch for staging deployment
  .github/workflows/stage.yml
Labels: maintenance

#282 Update develop branch
  .github/workflows/stage.yml
  package.json
  src/pages/optimizer/data-ingestion/api-reference.md
  src/pages/optimizer/data-ingestion/using-the-api.md
  src/pages/reference/rest/index.md
  yarn.lock
Labels: maintenance

#287 Replace tenant ID with instance ID
  src/_includes/authentication/get-tenant-id.md
  src/pages/credential/GetCredentialOAuthS2s.js
  src/pages/optimizer/admin/using-the-api.md
  src/pages/optimizer/data-ingestion/using-the-api.md
  src/pages/optimizer/merchandising-services/troubleshooting.md
  src/pages/optimizer/merchandising-services/using-the-api.md
Labels: editorial

#291 COMOPT-1000-update-merch-svcs-api-headers
  src/pages/optimizer/ccdm-use-case.md
  src/pages/optimizer/data-ingestion/using-the-api.md
  src/pages/optimizer/merchandising-services/using-the-api.md
Labels: technical

#293 Enable TENANT_ID env in spectaql config
  .env.example
  .gitignore
  package.json
  scripts/generate-spectaql-config.js
  scripts/run-spectaql-with-cleanup.js
  spectaql/README.md
  spectaql/config-storefront.yml
  static/graphql-api/admin-api/index.html
  static/graphql-api/merchandising-api/index.html
  yarn.lock
Labels: enhancement, maintenance

#296 Update data-ingestion-schema-v1.yaml
  src/_includes/authentication/get-new-bearer-token.md
  src/_includes/authentication/get-tenant-id.md
  src/_includes/authentication/initial-auth-for-api-access.md
  src/_includes/graphql/endpoints.md
  src/data/navigation/sections/optimizer.js
  src/pages/_images/merchandising/aco-instance-details.png
  src/pages/credential/GetCredentialOAuthS2s.js
  src/pages/live-search/index.md
  src/pages/optimizer/admin/using-the-api.md
  src/pages/optimizer/data-ingestion/api-testing.md
  src/pages/optimizer/data-ingestion/authentication.md
  src/pages/optimizer/data-ingestion/using-the-api.md
  src/pages/optimizer/merchandising-services/data-type-reference.md
  src/pages/optimizer/merchandising-services/troubleshooting.md
  src/pages/optimizer/merchandising-services/using-the-api.md
  static/graphql-api/merchandising-api/index.html
Labels: major-update
