Repository AdobeDocs/commerce-services, pull requests merged in 2025-01, with the labels that each got.

#182 MSRCH-4778: Update attribute-metadata.md with federated endpoint
  src/pages/graphql/live-search/attribute-metadata.md
Labels: technical

#169 DATA-6224: Update CCDM storefront API header descriptions
  src/pages/composable-catalog/storefront-services/using-the-api.md
Labels: editorial

#185 Hide the "categories" query
  spectaql/config-storefront.yml
  spectaql/metadata-storefront.json
  static/graphql-api/storefront-api/index.html
Labels: technical

#189 Add 'back to top' to GraphQL API docs
  spectaql/comdox-theme/views/partials/graphql/_query-or-mutation-or-subscription.hbs
  spectaql/comdox-theme/views/partials/graphql/type.hbs
  spectaql/config-admin.yml
  spectaql/config-storefront.yml
  static/graphql-api/admin-api/index.html
  static/graphql-api/storefront-api/index.html
Labels: enhancement
